---
- name: "Prepare - Scenario: Test Helix Removal"
  hosts:
    - all
  become: true
  gather_facts: false

  pre_tasks:

    - name: "Preparing Scenario"
      ansible.builtin.debug:
        msg: "Preparing Scenario"

- name: "Install Helix using PPA"
  ansible.builtin.import_playbook: "../shared/converge.yml"
