---
- name: Converge
  hosts:
    - all
  become: true

  # ---------------------------------------------------------------------------
  # ---------                          Roles                         ----------
  # ---------------------------------------------------------------------------

  roles:

    - name: "Scenario: Set up ansible-pull"
      role: "aaronvonawesome.initialize_ansible_pull"
      vars:
        var_ansible_pull_lts_codename: "wilma"
        var_ansible_pull_git_repo: "https://codeberg.org/aaronvonawesome/prime-pc.git"
        var_ansible_pull_playbook: "configure-prime-pc.yaml"
        var_cron_minute: "*/2"
