---
- name: Verify
  hosts:
    - PrimePC

  tasks:

    - name: "Run ansible --version command"
      ansible.builtin.command:
        cmd: ansible --version
      register: ansible_version_output
      ignore_errors: true

    - name: "Check if Ansible is installed and return an error if not"
      ansible.builtin.fail:
        msg: "Ansible is not installed on the target node."
      when: >
        ansible_version_output.stdout is not defined
        or
        ansible_version_output.stdout == ""

    - name: "Print the Ansible version"
      ansible.builtin.debug:
        msg: "Ansible version installed: {{ ansible_version_output.stdout }}"
      when: >
        ansible_version_output.stdout is defined
        and
        ansible_version_output.stdout != ""
