---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    _lts_codename: "{{ lts_codename }}"
    _user_list: "{{ user_list }}"


  tasks:

    - name: "Scenario: Test Docker install"
      ansible.builtin.include_role:
        name: "aaronvonawesome.install_docker"
      vars:
        var_lts_codename: "{{ _lts_codename }}"
        var_user_list: "{{ _user_list }}"
