---
#######################################################################
### ***        Prime PC Configuration - Playbook         ***  ###
#######################################################################


# ==================================================================================
# =====                     Play - Configure Prime PC                         ======
# ==================================================================================
#
- name: "Configure Prime PC"
  hosts:
    - all
  become: true
  vars_files:
    - "./tasks/vault/vars-files/configuration-vars.yaml"
  vars:
    _folder_list: "{{ vault_folder_list }}"
    _lts_codename: "noble"
    _molecule_version: "25.3.1"
    _node_version: "{{ vault_node_version }}"
    _should_install_ansible_community_docker_collection_compatibility: true
    _should_install_virtualbox: true
    _timezone: "{{ vault_timezone }}"
    _username: "{{ vault_username }}"




  # ---------------------------------------------------------------------------
  # ---------                          Pre-Tasks                     ----------
  # ---------------------------------------------------------------------------

  pre_tasks:

    - name: "Set Timezone"
      community.general.timezone:
        name: "{{ _timezone }}"

    - name: "Display the Inventory File Path"
      ansible.builtin.debug:
        var: ansible_inventory_sources

    - name: "Display the \"hostname\" as defined in the Inventory File"
      ansible.builtin.debug:
        msg: "Inventery File Host: {{ ansible_hostname }}"

    - name: "Display the ACTUAL \"hostname\""
      ansible.builtin.debug:
        msg: "The ACTUAL \"hostname\": {{ ansible_facts.hostname }}"

    - name: "-------> RUN: Enable snaps Tasks"
      include_tasks: tasks/enable-snaps.yaml




  # ---------------------------------------------------------------------------
  # ---------                          Roles                         ----------
  # ---------------------------------------------------------------------------

  roles:

    - name: "ROLE - Install Docker"
      role: "aaronvonawesome.install_docker"
      vars:
        var_docker_daemon_file: "install-docker_custom-docker-daemon.json"
        var_lts_codename: "{{ _lts_codename }}"
        var_should_install_ansible_community_docker_collection_compatibility: >
          {{ _should_install_ansible_community_docker_collection_compatibility }}
        var_user_list:
          - username: "{{ _username }}"


    # ======================     Desktop     ==================================

    - name: "ROLE - Install the Nextcloud Desktop Client"
      role: "aaronvonawesome.nextcloud_desktop_client"
      vars:
        var_lts_codename: "{{ _lts_codename }}"

    - name: "ROLE - Install Redshift"
      role: "aaronvonawesome.redshift"
      vars:
        var_redshift_username: "{{ _username }}"


    # ======================     Development     ==============================

    - name: "ROLE - Install Helix"
      role: "aaronvonawesome.helix"
      vars:
        var_lts_codename: "{{ _lts_codename }}"

    - name: "ROLE - Install Neovim"
      role: "aaronvonawesome.neovim"
      vars:
        var_lts_codename: "{{ _lts_codename }}"

    - name: "ROLE - Install Virtualbox + Vagrant"
      role: "aaronvonawesome.vagrant"
      vars:
        var_vagrant_username: "{{ _username }}"
        var_vagrant_should_install_virtualbox: "{{ _should_install_virtualbox }}"




  # ---------------------------------------------------------------------------
  # ---------                          Tasks                         ----------
  # ---------------------------------------------------------------------------

  tasks:

    - name: "-------> RUN: Setup Default Folders"
      include_tasks: tasks/default-folders.yaml
      vars:
        var_username: "{{ _username }}"
        var_folder_list: "{{ _folder_list }}"

    - name: "-------> RUN: Base Packages Tasks"
      include_tasks: tasks/base-packages.yaml


    # ======================     Desktop     ==================================

    - name: "-------> RUN: Desktop Packages Tasks"
      include_tasks: tasks/desktop-packages.yaml

    - name: "-------> RUN: Desktop Flatpaks Tasks"
      include_tasks: tasks/desktop-flatpaks.yaml


    # ======================     Development     ==============================

    - name: "-------> RUN: Development Packages Tasks"
      include_tasks: tasks/development-packages.yaml

    - name: "-------> RUN: Development Flatpaks Tasks"
      include_tasks: tasks/development-flatpaks.yaml

    - name: "-------> RUN: Development Snaps Tasks"
      include_tasks: tasks/development-snaps.yaml
      vars:
        var_node_version: "{{ _node_version }}"

    - name: "-------> RUN: Ansible Add-ons Pack Tasks"
      include_tasks: tasks/ansible-addons-pack.yaml
      vars:
        var_molecule_version: "{{ _molecule_version }}"
        var_username: "{{ _username }}"


    # ======================     Communication     ============================

    - name: "-------> RUN: Communication Flatpaks Tasks"
      include_tasks: tasks/communication-flatpaks.yaml


    # ======================     LLM-Related      =============================

    - name: "-------> RUN: AI/LLM Flatpaks Tasks"
      include_tasks: tasks/ai-llm-flatpaks.yaml


    # ======================     Browsers     =================================

    - name: "-------> RUN: Browser Packages Tasks"
      include_tasks: tasks/browser-packages.yaml

    - name: "-------> RUN: Browser Flatpaks Tasks"
      include_tasks: tasks/browser-flatpaks.yaml

    - name: "-------> RUN: Browser Snaps Tasks"
      include_tasks: tasks/browser-snaps.yaml
