---
#######################################################################
### ***        Prime PC Configuration - Playbook         ***  ###
#######################################################################


# ==================================================================================
# =====                     Play - Configure Prime PC                         ======
# ==================================================================================
#
- name: "Configure Prime PC"
  hosts:
    - all
  become: true
  vars:
    _lts_codename: "noble"
    _should_install_ansible_community_docker_collection_compatibility: true
  vars_files:
    - "./tasks/vault/vars-files/configuration-vars.yaml"

  # ---------------------------------------------------------------------------
  # ---------                          Roles                         ----------
  # ---------------------------------------------------------------------------

  roles:

    - name: "ROLE - Install Docker"
      role: "aaronvonawesome.install_docker"
      vars:
        var_docker_daemon_file: "install-docker_custom-docker-daemon.json"
        var_lts_codename: "{{ _lts_codename }}"
        var_should_install_ansible_community_docker_collection_compatibility: >
          {{ _should_install_ansible_community_docker_collection_compatibility }}
        var_user_list: "{{ vault_user_list }}"

    - name: "ROLE - Install Helix"
      role: "aaronvonawesome.helix"
      vars:
        var_lts_codename: "{{ _lts_codename }}"

    - name: "ROLE - Install Neovim"
      role: "aaronvonawesome.neovim"
      vars:
        var_lts_codename: "{{ _lts_codename }}"

    - name: "ROLE - Install the Nextcloud Desktop Client"
      role: "aaronvonawesome.nextcloud_desktop_client"
      vars:
        var_lts_codename: "{{ _lts_codename }}"


  # ---------------------------------------------------------------------------
  # ---------                          Tasks                         ----------
  # ---------------------------------------------------------------------------

  tasks:

    - name: "Set Timezone"
      community.general.timezone:
        name: "{{ vault_timezone }}"
