---
#######################################################################
### ***        Prime PC Configuration - Playbook         ***  ###
#######################################################################


# ==================================================================================
# =====                     Play - Configure Prime PC                         ======
# ==================================================================================
#
- name: "Configure Prime PC"
  hosts:
    - all
  become: true
  vars:
    _lts_codename: "noble"
    _user_list:
      - username: ""
      - username: ""


  # ---------------------------------------------------------------------------
  # ---------                          Tasks                         ----------
  # ---------------------------------------------------------------------------

  tasks:

    - name: "Set Timezone"
      community.general.timezone:
        name: "Asia/Singapore"
