---
name: ansible-dev-tools-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
      - ansible-navigator[ansible-core]==25.8.0
      - molecule==24.12.0
      - molecule-plugins[docker]==23.5.3
      - molecule-plugins[vagrant]==23.5.3
