---
###########################################################################
#                                                                         #
#            *** Ping for Testing Connectivity - Playbook ***             #
#                                                                         #
###########################################################################

# ===========================================================
# =====   Play - Ping Hosts
# ===========================================================
- name: Ping Hosts
  hosts: all
  gather_facts: false

  # -----------------------------------------
  # -----         TASKS                ------
  # -----------------------------------------

  tasks:

    - name: PING
      ping:
        data: "PONG"  # If this parameter is set to "crash", the module will cause an exception.
