---

roles:

  - name: "aaronvonawesome.initialize_ansible_pull"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-initialize-ansible-pull.git"
    version: "main"

  - name: "aaronvonawesome.install_docker"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-install-docker.git"
    version: "main"

  - name: "aaronvonawesome.helix"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-helix.git"
    version: "main"

  - name: "aaronvonawesome.neovim"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-neovim.git"
    version: "main"

  - name: "aaronvonawesome.nextcloud_desktop_client"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-nextcloud-desktop-client.git"
    version: "main"

  - name: "aaronvonawesome.vagrant"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-vagrant.git"
    version: "main"

  - name: "aaronvonawesome.conda"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-conda.git"
    version: "main"

  - name: "aaronvonawesome.yt_dlp"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-yt-dlp.git"
    version: "main"

  - name: "aaronvonawesome.onlykey_app"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-onlykey-app.git"
    version: "main"

  - name: "aaronvonawesome.proton_suite"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-proton-suite.git"
    version: "main"

  - name: "aaronvonawesome.lube_logger"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-lube-logger.git"
    version: "main"

  - name: "pluggero.lazygit"
  - name: "pluggero.nerdfonts"

  - name: "dbrennand.autorestic"


collections:

  - name: "community.general"
