---

roles:

  - name: "aaronvonawesome.initialize_ansible_pull"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-initialize-ansible-pull.git"
    version: "main"

  - name: "aaronvonawesome.install_docker"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-install-docker.git"
    version: "main"

  - name: "aaronvonawesome.helix"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-helix.git"
    version: "main"

  - name: "aaronvonawesome.neovim"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-neovim.git"
    version: "main"

  - name: "aaronvonawesome.nextcloud_desktop_client"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-nextcloud-desktop-client.git"
    version: "main"

  - name: "aaronvonawesome.redshift"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-redshift.git"
    version: "main"

  - name: "aaronvonawesome.vagrant"
    scm: git
    src: "https://codeberg.org/aaronvonawesome/ansible-role-vagrant.git"
    version: "main"

collections:

  - name: "community.general"
