---
- name: Converge
  hosts:
    - all
  become: true
  gather_facts: false
  vars:
    _lts_codename: "{{ lts_codename }}"


  tasks:

    - name: "Converge - Scenario: Test yt-dlp Install"
      ansible.builtin.include_role:
        name: "aaronvonawesome.yt_dlp"
      vars:
        yt_dlp_var_lts_codename: "{{ _lts_codename }}"
