---
- name: Converge
  hosts:
    - all
  become: true
  gather_facts: false


  tasks:

    - name: "Converge - Scenario: Test Proton Mail Bridge Install"
      ansible.builtin.include_role:
        name: "aaronvonawesome.proton_suite"
      vars:
        var_proton_suite_should_install_proton_mail_bridge: true
