---
# ============================================================
#                     communication-flatpaks.yaml
# ============================================================

- name: "Block: communication-flatpaks.yaml"
  become: true
  block:

    - name: "Install Communication flatpaks"
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: system
      loop:
        - chat.delta.desktop

  rescue:

    - name: "ERROR: communication-flatpaks.yaml"
      ansible.builtin.debug:
        msg: "ERROR: communication-flatpaks.yaml"

    - name: "Error detected! Stopping Playbook :-("
      ansible.builtin.fail:
        msg: "Error detected! Stopping Playbook :-("
