---
# ============================================================
#                     communication-flatpaks.yaml
# ============================================================

- name: "Block: communication-flatpaks.yaml"
  become: true
  block:

    - name: "Remove Communication flatpaks"
      community.general.flatpak:
        name: "{{ item }}"
        state: absent
        method: system
      loop:
        - io.github.qtox.qTox

    - name: "Install Communication flatpaks"
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: system
      loop:
        - chat.delta.desktop
        - im.dino.Dino
        - im.riot.Riot
        - network.loki.Session
        - org.briarproject.Briar
        - org.gajim.Gajim
        - org.signal.Signal

  rescue:

    - name: "ERROR: communication-flatpaks.yaml"
      ansible.builtin.debug:
        msg: "ERROR: communication-flatpaks.yaml"

    - name: "Error detected! Stopping Playbook :-("
      ansible.builtin.fail:
        msg: "Error detected! Stopping Playbook :-("
