---
# ============================================================
#                     media-snaps.yaml
# ============================================================

- name: "Block: media-snaps.yaml"
  become: true
  block:

    - name: "Remove freeshow Snap Package - beta"
      community.general.snap:
        name: freeshow
        state: absent
        channel: latest/beta

    - name: "Remove freeshow Snap Package - stable"
      community.general.snap:
        name: freeshow
        state: absent
        channel: latest/stable

  rescue:

    - name: "ERROR: media-snaps.yaml"
      ansible.builtin.debug:
        msg: "ERROR: media-snaps.yaml"

    - name: "Error detected! Stopping Playbook :-("
      ansible.builtin.fail:
        msg: "Error detected! Stopping Playbook :-("
