---
# ============================================================
#                     media-snaps.yaml
# ============================================================

- name: "Block: media-snaps.yaml"
  become: true
  block:

    - name: "TODO: Add Media Snaps here"
      ansible.builtin.debug:
        msg: "TODO: Add Media Snaps here"

  #  - name: "Install <some-snap> Snap Package"
  #    community.general.snap:
  #      name: <some-snap>
  #      state: present
  #      channel: latest/stable

  rescue:

    - name: "ERROR: media-snaps.yaml"
      ansible.builtin.debug:
        msg: "ERROR: media-snaps.yaml"

    - name: "Error detected! Stopping Playbook :-("
      ansible.builtin.fail:
        msg: "Error detected! Stopping Playbook :-("
