---
- name: Converge
  hosts:
    - all
  become: true
  gather_facts: false


  tasks:

    - name: "Converge - Scenario: Test conda Install"
      ansible.builtin.include_role:
        name: "aaronvonawesome.conda"
