---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    _username: "{{ username }}"

  tasks:

    - name: "Converge - Scenario: Test Redshift-gtk Install"
      ansible.builtin.include_role:
        name: "aaronvonawesome.redshift"
      vars:
        var_redshift_username: "{{ _username }}"
