---
prerun: false
dependency:
  name: galaxy
  enabled: false
driver:
  name: vagrant
platforms:
  - name: molecule-test-instance
    box: aaronvonawesome/linux-mint-22-cinnamon
    memory: 4096
    cpus: 2
    provider_raw_config_args:
      - "gui = ${SHOW_VAGRANT_VM_GUI:-false}"
      - "name = 'molecule-test-instance'"
      - "customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']"
      - "customize ['modifyvm', :id, '--vram', '128']"
      - "customize ['modifyvm', :id, '--accelerate3d', 'on']"
      - "customize ['modifyvm', :id, '--accelerate2dvideo', 'on']"
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_user: root
  env:
    ANSIBLE_COLLECTIONS_PATH: "../../collections"
    ANSIBLE_CONFIG: "../ansible.cfg"
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_VAULT_PASSWORD_FILE: "../../secret_vault-password-file"
    ANSIBLE_VERBOSITY: 0
  inventory:
    hosts:
      all:
        hosts:
          molecule-test-instance:
            lts_codename: "noble"
            username: "vagrant"
