---
scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  options:
    v: true
  config_options:
    defaults:
      remote_user: root
  env:
    ANSIBLE_CONFIG: "../../ansible.cfg"
    ANSIBLE_VAULT_PASSWORD_FILE: "../../secret_vault-password-file"
    ANSIBLE_VERBOSITY: 2
  inventory:
    group_vars:
      all:
        ansible_host: "localhost"
        ansible_python_interpreter: "/usr/bin/python3"
