---
prerun: false
dependency:
  name: galaxy
  enabled: false
scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_user: root
  env:
    ANSIBLE_COLLECTIONS_PATH: "../../collections"
    ANSIBLE_CONFIG: "../../ansible.cfg"
    ANSIBLE_ROLES_PATH: "../..roles"
    ANSIBLE_VAULT_PASSWORD_FILE: "../../secret_vault-password-file"
    ANSIBLE_VERBOSITY: 2
  inventory:
    group_vars:
      all:
        ansible_host: "localhost"
