---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    _username: "{{ username }}"

  tasks:

    - name: "Scenario: Install LubeLogger with default settings"
      ansible.builtin.include_role:
        name: "aaronvonawesome.lube_logger"
      vars:
        var_lube_logger_container_username: "{{ _username }}"
