---
# ============================================================
#                       Role: helix
# ============================================================


# ------------------------------------------------------------
#                       present
# ------------------------------------------------------------

- name: "Install Helix Editor"
  ansible.builtin.include_tasks: present.yaml
  when: >
    var_helix_state == "present"


# ------------------------------------------------------------
#                       absent
# ------------------------------------------------------------
#
- name: "Remove Helix Editor and PPA Source"
  ansible.builtin.include_tasks: absent.yaml
  when: >
    var_helix_state == "absent"
