---
# ============================================================
#                       Role: helix
# ============================================================

- name: "Block: Install Helix Ansible Role"
  become: true
  vars:
    _var_lts_codename: "{{ var_lts_codename }}"
  block:

    - name: "Add Helix Editor apt key"
      ansible.builtin.get_url:
        url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x355a4fa515d7c855"
        dest: "/etc/apt/trusted.gpg.d/helix.asc"
        mode: "0644"
        force: true
      changed_when: false

    - name: "Add Helix Editor repo to sources list"
      ansible.builtin.apt_repository:
        repo: >
          deb
          https://ppa.launchpadcontent.net/maveonair/helix-editor/ubuntu
          {{ _var_lts_codename }}
          main
        filename: "maveonair-helix-editor-{{ _var_lts_codename }}"
        update_cache: true
        mode: "0600"
      register: add_helix_repo_result
      until: add_helix_repo_result is succeeded
      retries: 3
      delay: 60
      ignore_errors: true

    - name: "Install Helix"
      ansible.builtin.apt:
        name: "helix"
        state: latest
        update_cache: true

  rescue:

    - name: "ERROR: Failed to install Helix"
      ansible.builtin.debug:
        msg: "ERROR: Failed to install Helix"

    - name: "Error detected! Stopping Playbook :-("
      ansible.builtin.fail:
        msg: "Error detected! Stopping Playbook :-("
