---
- name: Converge
  hosts:
    - all
  become: true

  tasks:

    - name: "Scenario: Test ansible-pull with SSH key"
      ansible.builtin.include_role:
        name: "aaronvonawesome.initialize_ansible_pull"
      vars:
        var_ansible_pull_lts_codename: "virginia"
