---
- name: Converge
  hosts:
    - all
  become: true

  tasks:

    - name: "Scenario: Install Ansible on Ubuntu Server 24.04"
      ansible.builtin.include_tasks: ../../tasks/install-latest-ansible.yaml
      vars:
        varLtsCodename: "noble"
