---
- name: Converge
  hosts:
    - all
  become: true

  tasks:

    - name: "Scenario: Install Ansible on Linux Mint 22"
      ansible.builtin.include_tasks: ../../tasks/install-latest-ansible.yaml
      vars:
        varLtsCodename: "wilma"
