---
- name: Verify
  hosts:
    - all
  gather_facts: false

  tasks:

    - name: "Check if Vagrant is installed"
      ansible.builtin.command:
        cmd: >
          which vagrant
      register: vagrant_installed
      ignore_errors: true

    - name: "Assert Vagrant is installed"
      ansible.builtin.assert:
        that:
          - vagrant_installed.rc == 0
        fail_msg: "Vagrant is not installed"
        success_msg: "Vagrant is installed"
