---
- name: Converge
  hosts: all
  gather_facts: false

  tasks:

    - name: "Scenario: Configure ansible-pull"
      ansible.builtin.include_role:
        name: "aaronvonawesome.initialize_ansible_pull"
      vars:
        var_ansible_pull_lts_codename: "virginia"
