---
driver:
  name: vagrant
platforms:
  - name: molecule-test-instance
    box: aaronvonawesome/docker-on-linux-mint
    memory: 4096
    cpus: 2
    provider_raw_config_args:
      - "gui = ${SHOW_VAGRANT_VM_GUI:-false}"
      - "name = 'molecule-test-instance'"
      - "customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']"
      - "customize ['modifyvm', :id, '--vram', '128']"
      - "customize ['modifyvm', :id, '--accelerate3d', 'on']"
      - "customize ['modifyvm', :id, '--accelerate2dvideo', 'on']"
provisioner:
  inventory:
    hosts:
      all:
        hosts:
          molecule-test-instance:
    host_vars:
      molecule-test-instance:
        username: "vagrant"
        lube_logger_docker_compose_directory: "/home/vagrant/Container-Apps/LubeLogger"
        container_apps_directory: "/home/vagrant/Container-Apps"
        should_deploy_with_swag_container: false
