---
- name: Prepare
  hosts:
    - all
  become: true
  gather_facts: false
  vars_files:
    - "../../tasks/vault/vars-files/configuration-vars.yaml"

  # -----------------------------------------
  # -----         TASKS                ------
  # -----------------------------------------
  tasks:


    - name: "Create Groups"
      ansible.builtin.group:
        name: "{{ vault_username }}"
        state: present

    - name: "Create Users"
      ansible.builtin.user:
        name: "{{ vault_username }}"
        create_home: true
        group: "{{ vault_username }}"
        groups: >
          {{ vault_username }},adm,cdrom,dialout,dip,lpadmin,plugdev,sambashare,sudo
        append: false
        shell: "/bin/bash"
