---
- name: Verify
  hosts:
    - PrimePC
  gather_facts: false

  # -----------------------------------------
  # -----         TASKS                ------
  # -----------------------------------------
  tasks:
