---
driver:
  name: docker
platforms:
  - name: molecule-test-instance
    image: docker.io/linuxmintd/mint22.1-amd64
    pre_build_image: true
provisioner:
  playbooks:
    prepare: ../shared/prepare.yml
    verify: ../shared/verify.yml
  inventory:
    hosts:
      all:
        hosts:
          molecule-test-instance:
    host_vars:
      molecule-test-instance:
        lube_logger_compose_with_default_network_input_filename: "lube-logger_compose-with-default-network.j2"
        should_deploy_with_swag_container: false
