---
- name: Converge
  hosts: all
  gather_facts: false

  tasks:

    - name: "Scenario: Install Ansible on Debian Bullseye"
      ansible.builtin.include_tasks: ../../tasks/install-latest-ansible.yaml
      vars:
        varLtsCodename: "bullseye"
