---
- name: Converge
  hosts:
    - all
  become: true

  tasks:

    - name: "Scenario: Ansible Install should fail if \"varLtsCodename\" is not set"
      ansible.builtin.include_tasks: ../../tasks/install-latest-ansible.yaml
