---
# ============================================================
#                     Role: redshift
# ============================================================

- name: "Get current latitude and longitude"
  ansible.builtin.uri:
    url: "http://ip-api.com/json"
    return_content: true
  register: location

- name: "Extract latitude and longitude"
  ansible.builtin.set_fact:
    var_redshift_latitude: "{{ location.json.lat }}"
    var_redshift_longitude: "{{ location.json.lon }}"


- name: "Block: \"redshift\" Ansible Role"
  become: true
  vars:
    _var_redshift_username: "{{ var_redshift_username }}"
    _var_redshift_temp_day: "{{ var_redshift_temp_day }}"
    _var_redshift_temp_night: "{{ var_redshift_temp_night }}"
    _var_redshift_gamma_day: "{{ var_redshift_gamma_day }}"
    _var_redshift_gamma_night: "{{ var_redshift_gamma_night }}"
    _var_redshift_latitude: "{{ var_redshift_latitude }}"
    _var_redshift_longitude: "{{ var_redshift_longitude }}"
    _var_redshift_config_filename: "{{ var_redshift_config_filename }}"

  block:

    - name: "Create Redshift config file for user {{ _var_redshift_username }}"
      become: true
      become_user: "{{ _var_redshift_username }}"
      block:

        - name: "Copy Redshift Config File to: /home/{{ _var_redshift_username }}/.config/{{ __var_redshift_config_file }}"
          ansible.builtin.template:
            src: "{{ lookup('first_found', file_paths) }}"
            dest: "/home/{{ _var_redshift_username }}/.config/{{ __var_redshift_config_file }}"
            owner: "{{ _var_redshift_username }}"
            group: "{{ _var_redshift_username }}"
            mode: "0664"
            force: true
          vars:
            file_paths:
              - "{{ _var_redshift_config_filename }}"
              - "{{ playbook_dir }}/files/{{ _var_redshift_config_filename }}"
              - "{{ role_path }}/files/{{ _var_redshift_config_filename }}"
          register: copy_redshift_config_file_result

      rescue:

        - name: "Did not set up Redshift Config file for user '{{ _var_redshift_username }}'"
          ansible.builtin.debug:
            msg: "Did not set up Redshift Config file for user '{{ _var_redshift_username }}'"

        - name: "Error detected! Stopping Playbook :-("
          ansible.builtin.fail:
            msg: "Error detected! Stopping Playbook :-("


    - name: "Install redshift-gtk"
      ansible.builtin.apt:
        name: "redshift-gtk"
        state: latest
        update_cache: true

  rescue:

    - name: "ERROR: \"redshift\" Ansible Role"
      ansible.builtin.debug:
        msg: "ERROR: \"redshift\" Ansible Role"

    - name: "Error detected! Stopping Playbook :-("
      ansible.builtin.fail:
        msg: "Error detected! Stopping Playbook :-("
