---
- name: Verify
  hosts:
    - all
  become: true
  gather_facts: false

  tasks:

    - name: "Check if 'vim' command will run 'nvim'"
      ansible.builtin.command:
        cmd: >
          bash -i -c 'vim --version | grep -q NVIM'
      register: _vim_command_will_run_nvim

    - name: "Assert 'vim' command will run Neovim"
      assert:
        that:
          - _vim_command_will_run_nvim.rc == 0
        fail_msg: "'vim' command does NOT run Neovim"
        success_msg: "'vim' command does run Neovim"

    - name: "Check if 'vi' command will run 'nvim'"
      ansible.builtin.command:
        cmd: >
          bash -i -c 'vi --version | grep -q NVIM'
      register: _vi_command_will_run_nvim

    - name: "Assert 'vi' command will run Neovim"
      assert:
        that:
          - _vi_command_will_run_nvim.rc == 0
        fail_msg: "'vi' command does NOT run Neovim"
        success_msg: "'vi' command does run Neovim"
