---
- name: Verify
  hosts:
    - all
  become: true
  gather_facts: false

  tasks:

    - name: "Check if Neovim is installed"
      ansible.builtin.command:
        cmd: >
          which nvim
      register: neovim_installed
      ignore_errors: true

    - name: "Assert Neovim is installed"
      assert:
        that:
          - neovim_installed.rc == 0
        fail_msg: "Neovim is not installed"
        success_msg: "Neovim is installed"
