---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    _lube_logger_docker_compose_directory: "{{ lube_logger_docker_compose_directory }}"
    _lube_logger_docker_compose_output_filename: "{{ lube_logger_docker_compose_output_filename }}"
    _lube_logger_compose_with_default_network_output_filename: "{{ lube_logger_compose_with_default_network_output_filename | default('') }}"
    _lube_logger_compose_with_swag_output_filename: "{{ lube_logger_compose_with_swag_output_filename | default('') }}"
    _should_deploy_with_swag_container: "{{ should_deploy_with_swag_container | bool }}"

  tasks:

    - name: "Set the Docker Compose Network file to be used"
      ansible.builtin.set_fact:
        _network_configuration_docker_compose_output_filename: "{{ _lube_logger_compose_with_swag_output_filename if _should_deploy_with_swag_container | bool else _lube_logger_compose_with_default_network_output_filename }}"

    - name: "Get the LubeLogger Docker Compose File"
      ansible.builtin.slurp:
        src: "{{ _lube_logger_docker_compose_directory }}/{{ _lube_logger_docker_compose_output_filename }}"
      register: _docker_compose_file

    - name: "Print contents of Docker Compose File: \"{{ _lube_logger_docker_compose_directory }}/{{ _lube_logger_docker_compose_output_filename }}\""
      ansible.builtin.debug:
        msg: "{{ _docker_compose_file.content | b64decode }}"

    - name: "Get the LubeLogger Docker Compose Network File"
      ansible.builtin.slurp:
        src: "{{ _lube_logger_docker_compose_directory }}/{{ _network_configuration_docker_compose_output_filename }}"
      register: _docker_compose_network_file

    - name: "Print contents of Docker Compose File: \"{{ _lube_logger_docker_compose_directory }}/{{ _network_configuration_docker_compose_output_filename }}\""
      ansible.builtin.debug:
        msg: "{{ _docker_compose_network_file.content | b64decode }}"
