---
- name: "Converge - Scenario: Ansible Add-ons Pack"
  hosts:
    - all
  become: true
  gather_facts: false
  vars:
    _username: "{{ username }}"
    _molecule_version: "{{ molecule_version }}"


  tasks:

    - name: "Run: apt-get update"
      apt:
        update_cache: true

    - name: "-------> RUN: Ansible Add-ons Pack Tasks"
      include_tasks: ../../tasks/ansible-addons-pack.yaml
      vars:
        var_molecule_version: "{{ _molecule_version }}"
        var_username: "{{ _username }}"
