---
- name: "Converge - Scenario: Ansible Add-ons Pack"
  hosts:
    - all
  become: true
  gather_facts: false
  vars:
    _username: "{{ username }}"


  tasks:

    - name: "Run: apt-get update"
      ansible.builtin.apt:
        update_cache: true

    - name: "-------> RUN: Ansible Add-ons Pack Tasks"
      include_tasks: ../../tasks/ansible-addons-pack.yaml
      vars:
        var_username: "{{ _username }}"
